# Email Template
# =================================================

email:
  default:
    from: dbreport
    subject: >
      Database Report: {{name}}
    body: |+
      {{conf.title}}
      ==========================================================================

      {{conf.description}}

      Started at {{dateFormat date "LLL"}}:

      | Zeilen | Datei    | Beschreibung |
      | ------:| -------- | ------------ |
      {{#each result}}
      | {{rows}} | {{file}} | {{description}} |
      {{/each}}

      Find the files attached to your mail if data available!
