# Email Templates
# =================================================


# Default Template
# -------------------------------------------------
# This will extend/overwrite the allready existing setup within the code.
default:
  # specify how to connect to the server
  transport: smtp://alexander.schilling%40anythere.net:<<<env://PW_ALEX_MAIL>>>@mail.anythere.net
  # sender address
  from: alexander.schilling@anythere.net

  # content
  locale: de
  subject: >
    {{conf.title}}
  body: |+
    {{conf.title}}
    ==========================================================================

    {{conf.description}}

    Ausgeführt am {{dateFormat date "LLLL"}}

    ::: info
    Die Ergebnisse liegen der Email als Anhang bei!
    :::

    Ausgeführte SQL Befehle
    --------------------------------------------------------------------------

    {{#each conf.query}}
    ### Abfrage '{{@key}}' auf {{database}}

    ``` sql
    {{command}}
    ```

    {{/each}}
